### ISSUE TITLE
Relative path for WordPress core files needs to be corrected.

### ISSUE THREAD

**Issue by gegere** [humanmade/wp-stripe#12]
PHP Warning:  require(../../../../wp-blog-header.php) [<a href='function.require'>function.require</a>]: failed to open stream: No such file or directory

**Comment by willmot** [comment]
I don't think that's related to this plugin

**Comment by gegere** [comment]
@willmot sorry for my lack of detail. Not sure why I included such a general issue. I do know I have this plugin as well as many others working with a [WordPress Skeleton Setup](https://github.com/htmlgraphic/WordPress-Skeleton)

When installing this plugin I think I had an issue... Anyway, carry on. :+1:
