### ISSUE TITLE
"Display on Website" checkbox still appears on form when Recent Widget is disabled

### ISSUE THREAD

**Issue by philipnewcomer** [humanmade/wp-stripe#2]
Hi, thanks for a great plugin!

The one issue I have is that even when the Recent Widget is turned off in the settings, the checkbox "Display on Website" still appears on the donation form. That is confusing people, who are worrying that their name will be shown publicly on the site. It would be great if when the Recent Widget is turned off in the settings, the checkbox on the form would be hidden as well.

Philip

**Comment by noeltock** [comment]
Hi Philip,

I've implemented this now!

Cheers

Noel

**Comment by philipnewcomer** [comment]
Excellent! Thanks again for a great plugin!
